name: "manual-action"

on:
    Workflow_dispatch

jobs:
    release:
        name: manual-action
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.4.2
            - name: node
              uses: actions/setup-node@v3.2.0
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org
            - name: ðŸš€ publish
              run: npm publish --access public
              working-directory: adsblock-detector
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}